const data = {
  products: [
    {
      id_list: 1,
      title: "CHĂM SÓC DA SKINCARE",
      genre: "SkinCare",
      category_name: "CHĂM SÓC DA SKINCARE",
      content: [
        {
          id: 1,
          img: "/img/product/SkinCare/Skin-kemduong-Forencos.jpg",
          name: "Kem dưỡng Forencos",
          price: 120000,
          thuonghieu: "Forencos",
          desc: "Dòng kem DUY NHẤT có tính ĐẶC TRỊ DA ĐA CHỨC NĂNG bởi nó có quá nhiều công dụng thần kỳ trong 1 hộp kem Là dòng kem đặc trị lão hoá da, da chảy sệ, nhăn nheo.  Giúp da được săn chắc, đàn hồi cao. Loại kem đầu tiên có thể dùng làm kem trị nhăn VÙNG MẮT, trị thâm quầng mắt hiệu quả. Cấp ẩm, dưỡng ẩm, khoá ẩm tuyệt vời. Loại bỏ dầu thừa, kiểm soát bã nhờn, giảm mụn trứng cá: mụn cám, đầu đen, mụn mủ,… nhanh chóng. Làm trắng sáng da từ gốc. Giúp da trắng mịn từ tế bào gốc. Chất kem dạng sữa, có tính đàn hồi cao, mỏng mịn. Apply lên kem tệp mịn vào da, không bết dính, không nhờn. Tạo cảm giác the mát.",
        },
        {
          id: 2,
          img: "/img/product/SkinCare/Skin-Kemphuchoi.jpg",
          name: "kem phu choi",
          price: 175000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 3,
          img: "/img/product/SkinCare/Skin-Mask.jpeg",
          name: "Mask Shrek Pack Tuýp",
          price: 175000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 4,
          img: "/img/product/SkinCare/Skin-Taytrang-rauma.jpg",
          name: "Tẩy trang rau má",
          price: 170000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 5,
          img: "/img/product/SkinCare/Skin-Tooner-nghệ.jpg",
          name: "Toner Cocoon Nghệ",
          price: 175000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 6,
          img: "/img/product/SkinCare/Skin-Sua-rua-mat.png",
          name: "Sữa rửa mặt Gel Senka",
          price: 110000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 7,
          img: "/img/product/SkinCare/Sklin-TayTrang.jpg",
          name: "Tẩy trang Byphasse 100ml",
          price: 75000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 8,
          img: "/img/product/SkinCare/Skin-Kem-duong.jpg",
          name: "Kem dưỡng phục hồi da Avene Cicalfate Cream",
          price: 360000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 9,
          img: "/img/product/SkinCare/Skin-Chiet-dau-tay-trang.jpg",
          name: "Chiết dầu tẩy trang the body shop 50ml",
          price: 999999,
          desc: "abc",
          thuonghieu: "Forencos",
        },
      ],
    },
    {
      title: "Chấm mụn",
      type: "Chấm mụn",
      genre: "SkinCare",
      category_name: "CHĂM SÓC DA SKINCARE",
      content: [
        {
          id: 1,
          img: "/img/product/dots acne/Dots-chammun.jpg",
          name: "CHẤM MỤN SOME BY MI",
          price: 250000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 2,
          img: "/img/product/dots acne/Dots-Chiet-umun.jpg",
          name: "CHIẾT Ủ MỤN MEDI-PEEL EXTRA SUPER 9 50ML",
          price: 130000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 3,
          img: "/img/product/dots acne/Dots-Dungdich-chammun.jpg",
          name: "DUNG DỊCH CHẤM MỤN BÍ ĐAO COCOON 5ML",
          price: 95000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 4,
          img: "/img/product/dots acne/Dots-dungdich-umun.jpg",
          name: "CHIẾT Ủ MỤN MEDI-PEEL EXTRA SUPER 9 PLUS",
          price: 200000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 5,
          img: "/img/product/dots acne/Dots-Gel-Muntham.jpg",
          name: "GEL TRỊ MỤN THÂM MEGADUO 15G",
          price: 165000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 6,
          img: "/img/product/dots acne/Dots-gel-Tea.jpg",
          name: "GEL TEE TREE",
          price: 195000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
      ],
    },
    {
      title: "Dưỡng mắt - Eye Care",
      type: "Dưỡng mắt - Eye Care",
      genre: "SkinCare",
      category_name: "CHĂM SÓC DA SKINCARE",
      content: [
        {
          id: 1,
          img: "/img/product/EyeCare/EYE-item1.jpg",
          name: "KEM MẮT CHỐNG LÃO HÓA",
          price: 269000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 2,
          img: "/img/product/EyeCare/EYE-item2.jpg",
          name: "KEM MẮT GIẢM QUẦNG THÂM BỌNG MẮT",
          price: 269000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 3,
          img: "/img/product/EyeCare/EYE-item3.jpg",
          name: "KEM MẮT MEISHOKU PLANCENTA",
          price: 225000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 4,
          img: "/img/product/EyeCare/EYE-item4.jpg",
          name: "KEM MẮT AHAC XANH 15 ML",
          price: 110000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 5,
          img: "/img/product/EyeCare/EYE-item5.jpg",
          name: "THANH LĂN DƯỠNG MẮT INNISFREE GREEN TEA SEED EYE ",
          price: 260000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 6,
          img: "/img/product/EyeCare/EYE-item6.jpg",
          name: "KEM MẮT AHC XANH 30ML",
          price: 150000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 7,
          img: "/img/product/EyeCare/EYE-item7.jpg",
          name: "KEM MẮT NARUKO HOA HỒNG NHUNG RỪNG",
          price: 260000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 8,
          img: "/img/product/EyeCare/EYE-item8.jpg",
          name: "LĂN MẮT JM HỒNG",
          price: 155000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
      ],
    },
    {
      id_list: 4,
      title: "SẢN PHẨM THEO COMBO",
      genre: "SALE",
      category_name: "CHƯƠNG TRÌNH SALE HIỆN TẠI",
      content: [
        {
          id: 1,
          img: "/img/productSales/sale-item1.jpg",
          name: "Combo tẩy trang + bông tẩy trang",
          price: 200000,
          thuonghieu: "Forencos",
          desc: "Dòng kem DUY NHẤT có tính ĐẶC TRỊ DA ĐA CHỨC NĂNG bởi nó có quá nhiều công dụng thần kỳ trong 1 hộp kem Là dòng kem đặc trị lão hoá da, da chảy sệ, nhăn nheo.  Giúp da được săn chắc, đàn hồi cao. Loại kem đầu tiên có thể dùng làm kem trị nhăn VÙNG MẮT, trị thâm quầng mắt hiệu quả. Cấp ẩm, dưỡng ẩm, khoá ẩm tuyệt vời. Loại bỏ dầu thừa, kiểm soát bã nhờn, giảm mụn trứng cá: mụn cám, đầu đen, mụn mủ,… nhanh chóng. Làm trắng sáng da từ gốc. Giúp da trắng mịn từ tế bào gốc. Chất kem dạng sữa, có tính đàn hồi cao, mỏng mịn. Apply lên kem tệp mịn vào da, không bết dính, không nhờn. Tạo cảm giác the mát.",
        },
        {
          id: 2,
          img: "/img/productSales/sale-item2.jpg",
          name: "Combo Mi giả + Keo dán mi",
          price: 99000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 3,
          img: "/img/productSales/sale-item3.jpg",
          name: "Combo kem dưỡng cien ngày đêm",
          price: 219000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 4,
          img: "/img/productSales/sale-item4.jpg",
          name: "Combo chì mày InnisFree  + Dao cạo mày",
          price: 100000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 5,
          img: "/img/productSales/sale-item5.jpg",
          name: "Combo kem nền + Mút tán nền",
          price: 999000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 6,
          img: "/img/productSales/sale-item6.jpg",
          name: "Combo kẻ mắt + Mascara",
          price: 439000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 7,
          img: "/img/productSales/sale-item7.jpg",
          name: "Combo dầu gội xả Tigi + Ủ tóc Tigi",
          price: 699900,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 8,
          img: "/img/productSales/sale-item8.jpg",
          name: "Combo sữa rửa mặt + Tẩy trang Simple",
          price: 360000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 9,
          img: "/img/productSales/sale-item9.jpg",
          name: "Combo tẩy trang + Toner Simple",
          price: 269000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
        {
          id: 10,
          img: "/img/productSales/sale-item10.jpg",
          name: "Combo sữa rửa mặt + Toner Simple",
          price: 269000,
          desc: "abc",
          thuonghieu: "Forencos",
        },
      ],
    },
  ],
};
export default data;
